name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to PythonAnywhere
        uses: docker://pythonanywherehelper/pythonanywhere-action:latest
        with:
          pythonanywhere_username: nslock14
          pythonanywhere_password: sinhloc1005LN#
          pythonanywhere_app_name: chembalanceapp_venv
          pythonanywhere_api_token: 6e402b2a90409c27aa8ccdd07c0d452690df689e
          project_path: ./  # Set this to the path of your Flask project
